import { useCallback, useEffect, useState } from 'react';
import { apiJson } from '../lib/api';

type AgendaSlot = { id: string; date: string; startTime: string; endTime: string; available: boolean; booked: boolean; reservation: { id: string; memberName: string | null; status: string } | null };
type TrainerAgenda = { trainerId: string; trainerName: string; photoUrl: string | null; slots: AgendaSlot[] };

export function PtAgendaTab() {
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [agenda, setAgenda] = useState<TrainerAgenda[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterTrainer, setFilterTrainer] = useState('all');
  const [selectedAction, setSelectedAction] = useState<{ slot: AgendaSlot | null; trainer: TrainerAgenda; hour: string; type: 'available' | 'booked' | 'empty' } | null>(null);
  const [actionMode, setActionMode] = useState<'menu' | 'book' | 'bulkSlot' | 'reschedule' | null>(null);
  const [actionLoading, setActionLoading] = useState(false);
  const [allMembers, setAllMembers] = useState<Array<{ id: string; firstName: string; lastName: string; email: string; phone: string | null; ptSessions: number }>>([]);
  const [memberSearch, setMemberSearch] = useState('');
  const [selectedMember, setSelectedMember] = useState<{ id: string; firstName: string; lastName: string } | null>(null);
  const [bulkStartHour, setBulkStartHour] = useState(9);
  const [bulkEndHour, setBulkEndHour] = useState(18);
  const [rescheduleDate, setRescheduleDate] = useState('');
  const [rescheduleHour, setRescheduleHour] = useState('09');
  const [dragData, setDragData] = useState<{ reservationId: string; fromTrainerId: string; fromHour: string } | null>(null);
  const [dropTarget, setDropTarget] = useState<{ trainerId: string; hour: string } | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try { const [data, members] = await Promise.all([apiJson<TrainerAgenda[]>(`/admin/trainers/agenda?from=${date}&to=${date}`), apiJson<Array<{ id: string; firstName: string; lastName: string; email: string; phone: string | null; ptSessions: number }>>('/admin/members?status=active')]); setAgenda(data); setAllMembers(members); } catch { /* */ } finally { setLoading(false); }
  }, [date]);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);

  function navigateDate(off: number) { const d = new Date(date); d.setDate(d.getDate() + off); setDate(d.toISOString().slice(0, 10)); }
  function openSlotMenu(slot: AgendaSlot | null, trainer: TrainerAgenda, hour: string) { setSelectedAction({ slot, trainer, hour, type: slot ? (slot.booked ? 'booked' : 'available') : 'empty' }); setActionMode('menu'); setSelectedMember(null); setMemberSearch(''); }
  function closeModal() { setSelectedAction(null); setActionMode(null); setSelectedMember(null); setMemberSearch(''); }
  function openBulkSlotMenu(trainer: TrainerAgenda) { setSelectedAction({ slot: null, trainer, hour: '09:00', type: 'empty' }); setActionMode('bulkSlot'); setBulkStartHour(9); setBulkEndHour(18); }

  async function handleClearDay(trainer: TrainerAgenda) { if (!confirm(`${trainer.trainerName} — ${date} tüm slotlar silinecek?`)) return; try { await apiJson(`/admin/trainers/${trainer.trainerId}/schedule-day?date=${date}`, { method: 'DELETE' }); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } }
  async function handleBulkAddSlots() { if (!selectedAction) return; setActionLoading(true); try { const p = []; for (let h = bulkStartHour; h < bulkEndHour; h++) p.push(apiJson(`/admin/trainers/${selectedAction.trainer.trainerId}/schedule`, { method: 'POST', body: JSON.stringify({ date, startTime: `${String(h).padStart(2,'0')}:00`, endTime: `${String(h+1).padStart(2,'0')}:00` }) }).catch(() => null)); await Promise.all(p); closeModal(); void load(); } catch { /* */ } finally { setActionLoading(false); } }
  async function handleAddSlot() { if (!selectedAction) return; setActionLoading(true); try { await apiJson(`/admin/trainers/${selectedAction.trainer.trainerId}/schedule`, { method: 'POST', body: JSON.stringify({ date, startTime: selectedAction.hour, endTime: `${String(parseInt(selectedAction.hour)+1).padStart(2,'0')}:00` }) }); closeModal(); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } finally { setActionLoading(false); } }
  async function handleDeleteSlot() { if (!selectedAction?.slot || !confirm('Slot silinecek?')) return; setActionLoading(true); try { await apiJson(`/admin/trainers/${selectedAction.trainer.trainerId}/schedule/${selectedAction.slot.id}`, { method: 'DELETE' }); closeModal(); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } finally { setActionLoading(false); } }
  async function handleCancelReservation() { if (!selectedAction?.slot?.reservation || !confirm('İptal edilecek?')) return; setActionLoading(true); try { await apiJson(`/admin/reservations/${selectedAction.slot.reservation.id}/cancel`, { method: 'POST' }); closeModal(); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } finally { setActionLoading(false); } }
  async function handleCompleteReservation() { if (!selectedAction?.slot?.reservation) return; setActionLoading(true); try { await apiJson(`/admin/reservations/${selectedAction.slot.reservation.id}/complete`, { method: 'POST' }); closeModal(); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } finally { setActionLoading(false); } }
  async function handleBookSlot() { if (!selectedAction || !selectedMember) return; setActionLoading(true); try { const st = selectedAction.slot?.startTime || selectedAction.hour; await apiJson('/admin/reservations/create', { method: 'POST', body: JSON.stringify({ trainerId: selectedAction.trainer.trainerId, userId: selectedMember.id, date, startTime: st, endTime: `${String(parseInt(st)+1).padStart(2,'0')}:00` }) }); closeModal(); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Hata'); } finally { setActionLoading(false); } }
  function handleDragStart(e: React.DragEvent, rid: string, tid: string, h: string) { setDragData({ reservationId: rid, fromTrainerId: tid, fromHour: h }); e.dataTransfer.effectAllowed = 'move'; }
  function handleDragOver(e: React.DragEvent, tid: string, h: string) { e.preventDefault(); setDropTarget({ trainerId: tid, hour: h }); }
  function handleDragLeave() { setDropTarget(null); }
  async function handleDrop(e: React.DragEvent, tid: string, th: string) { e.preventDefault(); setDropTarget(null); if (!dragData) return; if (dragData.fromTrainerId === tid && dragData.fromHour === th) { setDragData(null); return; } try { await apiJson(`/admin/reservations/${dragData.reservationId}/reschedule`, { method: 'POST', body: JSON.stringify({ newDate: date, newStartTime: th, newEndTime: `${String(parseInt(th)+1).padStart(2,'0')}:00` }) }); void load(); } catch (err) { alert(err instanceof Error ? err.message : 'Taşıma başarısız'); } setDragData(null); }
  function handleDragEnd() { setDragData(null); setDropTarget(null); }

  const filteredAgenda = filterTrainer === 'all' ? agenda : agenda.filter(t => t.trainerId === filterTrainer);
  const allSlotTimes = filteredAgenda.flatMap(t => t.slots.filter(s => s.date === date).map(s => parseInt(s.startTime)));
  const minHour = allSlotTimes.length > 0 ? Math.min(...allSlotTimes) : 9;
  const maxHour = allSlotTimes.length > 0 ? Math.max(...allSlotTimes) + 1 : 22;
  const hours = Array.from({ length: maxHour - minHour }, (_, i) => `${String(i + minHour).padStart(2, '0')}:00`);
  const totalSlots = filteredAgenda.reduce((s, t) => s + t.slots.filter(sl => sl.date === date).length, 0);
  const bookedSlots = filteredAgenda.reduce((s, t) => s + t.slots.filter(sl => sl.date === date && sl.booked).length, 0);
  const occupancyPct = totalSlots > 0 ? Math.round((bookedSlots / totalSlots) * 100) : 0;
  const filteredMembers = memberSearch.length > 0 ? allMembers.filter(m => `${m.firstName} ${m.lastName} ${m.email}`.toLowerCase().includes(memberSearch.toLowerCase())).slice(0, 10) : allMembers.slice(0, 10);


  return (
    <div>
      <div className="agenda-toolbar"><div className="agenda-nav"><button className="btn-sm btn-outline" onClick={() => navigateDate(-1)}>‹</button><button className="btn-sm btn-outline" onClick={() => setDate(new Date().toISOString().slice(0,10))}>Bugün</button><button className="btn-sm btn-outline" onClick={() => navigateDate(1)}>›</button><span className="agenda-date-label">{new Date(date).toLocaleDateString('tr-TR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</span></div><div className="agenda-view-toggle"><select className="form-input" style={{ minWidth: 160 }} value={filterTrainer} onChange={(e) => setFilterTrainer(e.target.value)}><option value="all">Tüm Eğitmenler</option>{agenda.map(t => <option key={t.trainerId} value={t.trainerId}>{t.trainerName}</option>)}</select></div></div>

      {!loading && totalSlots > 0 && (<div className="agenda-stats-bar"><div className="agenda-stat"><span className="agenda-stat-value">{bookedSlots}</span><span className="agenda-stat-label">Ders</span></div><div className="agenda-stat"><span className="agenda-stat-value">{totalSlots - bookedSlots}</span><span className="agenda-stat-label">Müsait</span></div><div className="agenda-stat"><span className="agenda-stat-value">{totalSlots}</span><span className="agenda-stat-label">Toplam</span></div><div className="agenda-stat"><span className="agenda-stat-value" style={{ color: occupancyPct >= 80 ? '#059669' : occupancyPct >= 50 ? '#d97706' : '#64748b' }}>%{occupancyPct}</span><span className="agenda-stat-label">Doluluk</span></div><div className="agenda-legend"><span className="agenda-legend-item"><span className="agenda-legend-dot" style={{ background: '#22c55e' }}></span>Müsait</span><span className="agenda-legend-item"><span className="agenda-legend-dot" style={{ background: '#2563eb' }}></span>Dolu</span><span className="agenda-legend-item"><span className="agenda-legend-dot" style={{ background: '#e2e8f0' }}></span>Slot Yok</span></div></div>)}

      {loading && <p className="muted">Yükleniyor...</p>}
      {!loading && agenda.length === 0 && <div className="empty-state"><span className="empty-icon">🏋️</span><p>Eğitmen veya slot bulunamadı.</p></div>}

      {!loading && filteredAgenda.length > 0 && (<div className="agenda-grid-wrapper"><table className="agenda-table"><thead><tr><th className="agenda-th-hour">Saat</th>{filteredAgenda.map(t => { const ds = t.slots.filter(s => s.date === date); return (<th key={t.trainerId} className="agenda-th-therapist"><div style={{ cursor:'pointer' }} onClick={() => openBulkSlotMenu(t)}>{t.photoUrl && <img src={t.photoUrl} alt="" className="agenda-avatar" />}<div className="agenda-therapist-name">{t.trainerName}</div><div className="agenda-therapist-stat">{ds.filter(s=>s.booked).length}/{ds.length} dolu</div></div>{ds.length > 0 && <button className="agenda-clear-btn" onClick={(e) => { e.stopPropagation(); void handleClearDay(t); }}>✕ Günü Kapat</button>}</th>);})}</tr></thead>
        <tbody>{hours.map(h => { const nH = `${String(parseInt(h)+1).padStart(2,'0')}:00`; const now = new Date(); const isPast = date === now.toISOString().slice(0,10) && parseInt(h) < now.getHours(); return (<tr key={h} className={isPast ? 'agenda-row-past' : ''}><td className="agenda-td-hour">{h}–{nH}</td>{filteredAgenda.map(t => { const slot = t.slots.filter(s=>s.date===date).find(s=>s.startTime===h); if (!slot) return <td key={t.trainerId} className={`agenda-td agenda-td-empty ${isPast?'agenda-td-past':''} ${dropTarget?.trainerId===t.trainerId&&dropTarget?.hour===h?'agenda-td-drop-target':''}`} onClick={isPast?undefined:()=>openSlotMenu(null,t,h)} onDragOver={isPast?undefined:(e)=>handleDragOver(e,t.trainerId,h)} onDragLeave={handleDragLeave} onDrop={isPast?undefined:(e)=>void handleDrop(e,t.trainerId,h)}><span className="agenda-empty-plus">{isPast?'—':dropTarget?.trainerId===t.trainerId&&dropTarget?.hour===h?'⬇':'+'}</span></td>; if (slot.booked&&slot.reservation) return <td key={t.trainerId} className={`agenda-td agenda-td-booked ${isPast?'agenda-td-past':'agenda-td-draggable'}`} draggable={!isPast} onDragStart={isPast?undefined:(e)=>handleDragStart(e,slot.reservation!.id,t.trainerId,h)} onDragEnd={handleDragEnd} onClick={()=>openSlotMenu(slot,t,h)}><div className="agenda-td-content"><span className="agenda-td-name">{slot.reservation.memberName?.split(' ')[0]||'—'}</span><span className="agenda-td-status">{slot.reservation.status==='confirmed'?'✓':'⏳'}</span></div></td>; return <td key={t.trainerId} className={`agenda-td agenda-td-free ${isPast?'agenda-td-past':''} ${dropTarget?.trainerId===t.trainerId&&dropTarget?.hour===h?'agenda-td-drop-target':''}`} onClick={isPast?undefined:()=>openSlotMenu(slot,t,h)} onDragOver={isPast?undefined:(e)=>handleDragOver(e,t.trainerId,h)} onDragLeave={handleDragLeave} onDrop={isPast?undefined:(e)=>void handleDrop(e,t.trainerId,h)}><span className="agenda-free-label">{isPast?'—':dropTarget?.trainerId===t.trainerId&&dropTarget?.hour===h?'⬇ Bırak':'Müsait'}</span></td>; })}</tr>);})}</tbody></table></div>)}

      {selectedAction && actionMode && (<div className="agenda-modal-overlay" onClick={closeModal}><div className="agenda-modal" onClick={(e)=>e.stopPropagation()}>
        {actionMode==='menu'&&selectedAction.type==='empty'&&(<><div className="agenda-modal-header"><h3>➕ Boş Slot</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-info"><span>🏋️ {selectedAction.trainer.trainerName}</span><span>🕐 {selectedAction.hour}–{String(parseInt(selectedAction.hour)+1).padStart(2,'0')}:00</span></div><div className="agenda-modal-actions"><button className="agenda-action-btn agenda-action-book" onClick={()=>void handleAddSlot()} disabled={actionLoading}>{actionLoading?'⏳...':'➕ Slot Ekle'}</button></div></>)}
        {actionMode==='menu'&&selectedAction.type==='available'&&(<><div className="agenda-modal-header"><h3>🟢 Müsait</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-info"><span>🏋️ {selectedAction.trainer.trainerName}</span><span>🕐 {selectedAction.slot?.startTime}–{selectedAction.slot?.endTime}</span></div><div className="agenda-modal-actions"><button className="agenda-action-btn agenda-action-book" onClick={()=>setActionMode('book')}>📅 Ders Oluştur</button><button className="agenda-action-btn agenda-action-cancel" onClick={()=>void handleDeleteSlot()} disabled={actionLoading}>🚫 Slotu Sil</button></div></>)}
        {actionMode==='menu'&&selectedAction.type==='booked'&&(<><div className="agenda-modal-header"><h3>🔵 Ders</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-info"><span>👤 {selectedAction.slot?.reservation?.memberName||'—'}</span><span>🏋️ {selectedAction.trainer.trainerName}</span><span>🕐 {selectedAction.slot?.startTime}–{selectedAction.slot?.endTime}</span></div><div className="agenda-modal-actions"><button className="agenda-action-btn agenda-action-complete" onClick={()=>void handleCompleteReservation()} disabled={actionLoading}>✅ Tamamlandı</button><button className="agenda-action-btn agenda-action-cancel" onClick={()=>void handleCancelReservation()} disabled={actionLoading}>❌ İptal</button><button className="agenda-action-btn agenda-action-book" onClick={()=>{setRescheduleDate(date);setRescheduleHour(selectedAction?.slot?.startTime?.slice(0,2)||'09');setActionMode('reschedule');}}>📅 İleri Tarihe Al</button><button className="agenda-action-btn agenda-action-book" onClick={()=>{if(selectedAction?.slot?.reservation){void apiJson(`/admin/reservations/${selectedAction.slot.reservation.id}/remind`,{method:'POST'}).then(()=>alert('✅ Hatırlatma gönderildi')).catch(()=>alert('Gönderilemedi'));}}}>📱 Hatırlatma</button></div></>)}
        {actionMode==='book'&&(<><div className="agenda-modal-header"><h3>📅 Ders Oluştur</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-info"><span>🏋️ {selectedAction.trainer.trainerName}</span><span>🕐 {selectedAction.slot?.startTime||selectedAction.hour}–{selectedAction.slot?.endTime||`${String(parseInt(selectedAction.hour)+1).padStart(2,'0')}:00`}</span></div><div className="agenda-modal-form"><label className="form-label">Üye Seç</label><input type="text" className="form-input" placeholder="İsim ile ara..." value={memberSearch} onChange={(e)=>setMemberSearch(e.target.value)} />{selectedMember?<div className="agenda-selected-member">✅ {selectedMember.firstName} {selectedMember.lastName}<button className="btn-sm btn-outline" style={{marginLeft:8,padding:'2px 8px',fontSize:'0.7rem'}} onClick={()=>setSelectedMember(null)}>Değiştir</button></div>:<div className="agenda-member-list">{filteredMembers.map(m=><div key={m.id} className="agenda-member-item" onClick={()=>setSelectedMember(m)}><div style={{display:'flex',justifyContent:'space-between',width:'100%'}}><div><strong>{m.firstName} {m.lastName}</strong><span style={{fontSize:'0.72rem',color:'var(--muted)',display:'block'}}>{m.email}</span></div>{m.ptSessions>0?<span style={{fontSize:'0.7rem',fontWeight:700,padding:'2px 8px',borderRadius:6,background:'#dcfce7',color:'#166534'}}>🏋️ {m.ptSessions}</span>:<span style={{fontSize:'0.7rem',padding:'2px 8px',borderRadius:6,background:'#f1f5f9',color:'#64748b'}}>Paket yok</span>}</div></div>)}</div>}<div style={{display:'flex',gap:'0.5rem',marginTop:'0.75rem'}}><button className="btn-sm btn-primary" disabled={!selectedMember||actionLoading} onClick={()=>void handleBookSlot()}>{actionLoading?'⏳...':'✓ Oluştur'}</button><button className="btn-sm btn-outline" onClick={()=>setActionMode('menu')}>Geri</button></div></div></>)}
        {actionMode==='reschedule'&&selectedAction?.slot?.reservation&&(<><div className="agenda-modal-header"><h3>📅 İleri Tarihe Al</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-form"><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'0.75rem'}}><label style={{display:'flex',flexDirection:'column',gap:'0.3rem'}}><span className="form-label">Tarih</span><input type="date" value={rescheduleDate} onChange={(e)=>setRescheduleDate(e.target.value)} className="form-input" min={new Date().toISOString().slice(0,10)} /></label><label style={{display:'flex',flexDirection:'column',gap:'0.3rem'}}><span className="form-label">Saat</span><select value={rescheduleHour} onChange={(e)=>setRescheduleHour(e.target.value)} className="form-input">{Array.from({length:16},(_,i)=>i+6).map(h=><option key={h} value={String(h).padStart(2,'0')}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><div style={{display:'flex',gap:'0.5rem',marginTop:'1rem'}}><button className="btn-sm btn-primary" disabled={actionLoading||!rescheduleDate} onClick={()=>{setActionLoading(true);apiJson(`/admin/reservations/${selectedAction!.slot!.reservation!.id}/reschedule`,{method:'POST',body:JSON.stringify({newDate:rescheduleDate,newStartTime:`${rescheduleHour}:00`,newEndTime:`${String(parseInt(rescheduleHour)+1).padStart(2,'0')}:00`})}).then(()=>{closeModal();void load();}).catch((err:unknown)=>alert(err instanceof Error?err.message:'Hata')).finally(()=>setActionLoading(false));}}>{actionLoading?'⏳...':'✓ Güncelle'}</button><button className="btn-sm btn-outline" onClick={()=>setActionMode('menu')}>Geri</button></div></div></>)}
        {actionMode==='bulkSlot'&&selectedAction&&(<><div className="agenda-modal-header"><h3>🕐 Çalışma Saati</h3><button className="agenda-modal-close" onClick={closeModal}>✕</button></div><div className="agenda-modal-info"><span>🏋️ {selectedAction.trainer.trainerName}</span><span>📅 {new Date(date).toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'})}</span></div><div className="agenda-modal-form"><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'0.75rem'}}><label style={{display:'flex',flexDirection:'column',gap:'0.3rem'}}><span className="form-label">Başlangıç</span><select value={bulkStartHour} onChange={(e)=>setBulkStartHour(Number(e.target.value))} className="form-input">{Array.from({length:16},(_,i)=>i+6).map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label style={{display:'flex',flexDirection:'column',gap:'0.3rem'}}><span className="form-label">Bitiş</span><select value={bulkEndHour} onChange={(e)=>setBulkEndHour(Number(e.target.value))} className="form-input">{Array.from({length:16},(_,i)=>i+7).map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><p style={{fontSize:'0.8rem',fontWeight:600,margin:'0.5rem 0 0'}}>{bulkEndHour-bulkStartHour} slot</p><div style={{display:'flex',gap:'0.5rem',marginTop:'1rem'}}><button className="btn-sm btn-primary" disabled={actionLoading||bulkEndHour<=bulkStartHour} onClick={()=>void handleBulkAddSlots()}>{actionLoading?'⏳...':`✓ ${bulkEndHour-bulkStartHour} Slot`}</button><button className="btn-sm btn-outline" onClick={closeModal}>İptal</button></div></div></>)}
      </div></div>)}
    </div>
  );
}
